### ISSUE TITLE
Extra styling for Bootswatch skins

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/nodebb-theme-vanilla#42]
Some of the skins could use some minor adjustments regarding padding, margins (esp the top bar), and stuff like that. In general the colour schemes tend to work out, at least on vanilla, so that should be okay

In order to accomplish this in core we probably need to add a {skinName} class to the body if a skin was chosen

**Comment by robjens** [comment]
> In order to accomplish this in core we probably need to add a {skinName} class to the body if a skin was chosen

I would very much favor such an approach as it makes it even easier to narrow down changes to particular theme instances.

**Comment by psychobunny** [comment]
Addressed(ing) for persona, probably not going to make the effort for vanilla unless there's a demand
