### ISSUE TITLE
Problem with nodebb vanilla theme

### ISSUE THREAD

**Issue by kacemlight** [NodeBB/nodebb-theme-vanilla#50]
When I install I got this : 

npm WARN package.json reds@0.2.4 No repository field. npm ERR! 
peerinvalid The package nodebb-theme-vanilla does not satisfy its siblings' peerDependencies requirements!
 npm ERR! peerinvalid Peer nodebb-plugin-spam-be-gone@0.4.0 wants nodebb-theme-vanilla@>=0.0.137
 npm ERR! peerinvalid Peer nodebb-theme-lavender@0.2.6 wants nodebb-theme-vanilla@^0.2.0
 npm ERR! peerinvalid Peer nodebb-theme-cerulean@0.0.13-2 wants nodebb-theme-vanilla@~0.0.13 

 npm ERR! System Linux 3.16.0-23-generic 
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "i" "nodebb-plugin-sso-facebook@0.3.0"
npm ERR! cwd /opt/kae
npm ERR! node -v v0.10.25
 npm ERR! npm -v 1.4.21
npm ERR! code EPEERINVALID 
npm ERR! npm ERR! Additional logging details can be found in:
 npm ERR! /opt/kae/npm-debug.log
 npm ERR! not ok code 0

Can someone please tell me how to fix this problem, because my nodebb pages don't display correctely !!! ?

**Comment by julianlam** [comment]
@kacemlight Please run the following:

``` bash
$ cd /path/to/my/nodebb
$ npm unl nodebb-plugin-spam-be-gone nodebb-theme-vanilla
$ npm i nodebb-theme vanilla
$ npm i nodebb-plugin-spam-be-gone
```

**Comment by kacemlight** [comment]
No ti doesn't work ...  
![capture d ecran 2015-02-10 a 19 42 33](https://cloud.githubusercontent.com/assets/10455208/6133096/d3eb2aae-b157-11e4-8124-4c84817c0276.png)

**Comment by kacemlight** [comment]
For more visibly: 

kacemlight@NodeCommunity:~/mynodebb$ npm i nodebb-theme vanilla
npm WARN package.json nodebb-plugin-dbsearch@0.1.1 No repository field.
npm ERR! 404 404 Not Found: nodebb-theme
npm ERR! 404 
npm ERR! 404 'nodebb-theme' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'nodebb'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 3.13.0-32-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "i" "nodebb-theme" "vanilla"
npm ERR! cwd /home/kacemlight/mynodebb
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code E404
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/kacemlight/mynodebb/npm-debug.log
npm ERR! not ok code 0
kacemlight@NodeCommunity:~/mynodebb$ npm i nodebb-plugin-spam-be-gone
npm WARN package.json nodebb-plugin-dbsearch@0.1.1 No repository field.
npm ERR! peerinvalid The package nodebb-theme-vanilla does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer nodebb-plugin-spam-be-gone@0.4.0 wants nodebb-theme-vanilla@>=0.0.137
npm ERR! peerinvalid Peer nodebb-theme-lavender@0.2.13 wants nodebb-theme-vanilla@^0.2.0

npm ERR! System Linux 3.13.0-32-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "i" "nodebb-plugin-spam-be-gone"
npm ERR! cwd /home/kacemlight/mynodebb
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code EPEERINVALID
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/kacemlight/mynodebb/npm-debug.log
npm ERR! not ok code 0
kacemlight@NodeCommunity:~/mynodebb$

**Comment by julianlam** [comment]
Sorry, also remove the lavender theme, and reinstall it.

**Comment by kacemlight** [comment]
I did this also and I install the vanilla@^0.2.0 to satisfy lavender dependencies.. But I have always the problem on my login page :(

Terminal : kacemlight@NodeCommunity:~/mynodebb$ npm unl nodebb-plugin-spam-be-gone nodebb-theme-vanilla
npm WARN uninstall not installed in /home/kacemlight/mynodebb/node_modules: "nodebb-plugin-spam-be-gone"
unbuild nodebb-theme-vanilla@1.0.1
kacemlight@NodeCommunity:~/mynodebb$  npm i nodebb-theme-vanilla@^0.2.0
npm WARN package.json nodebb-plugin-dbsearch@0.1.1 No repository field.
nodebb-theme-vanilla@0.2.36 node_modules/nodebb-theme-vanilla
kacemlight@NodeCommunity:~/mynodebb$ npm i nodebb-theme-lavender
npm WARN package.json nodebb-plugin-dbsearch@0.1.1 No repository field.
nodebb-theme-lavender@0.2.13 node_modules/nodebb-theme-lavender
kacemlight@NodeCommunity:~/mynodebb$ npm i nodebb-plugin-spam-be-gone
npm WARN package.json nodebb-plugin-dbsearch@0.1.1 No repository field.
nodebb-plugin-spam-be-gone@0.4.0 node_modules/nodebb-plugin-spam-be-gone
├── project-honeypot@0.0.0
├── akismet@0.0.13
└── simple-recaptcha@1.0.0
kacemlight@NodeCommunity:~/mynodebb$ node app
10/2 13:30 [27509] - info: NodeBB v0.7.0-dev Copyright (C) 2013-2014 NodeBB Inc.
10/2 13:30 [27509] - info: This program comes with ABSOLUTELY NO WARRANTY.
10/2 13:30 [27509] - info: This is free software, and you are welcome to redistribute it under certain conditions.
10/2 13:30 [27509] - info: 
10/2 13:30 [27509] - info: Time: Tue Feb 10 2015 13:30:45 GMT-0500 (EST)
10/2 13:30 [27509] - info: Initializing NodeBB v0.7.0-dev
10/2 13:30 [27509] - info: Enabling 'trust proxy'
10/2 13:30 [27509] - info: NodeBB is now listening on: 0.0.0.0:4567
10/2 13:30 [27509] - info: NodeBB Ready



But on my page : 

![capture d ecran 2015-02-10 a 20 14 41](https://cloud.githubusercontent.com/assets/10455208/6133702/22452eda-b15c-11e4-81d6-5b41f6ccf0b7.png)


Is this has a relation with the theme problem ?

**Comment by kacemlight** [comment]
As you can see, on my login page I cannot find the fields ?

**Comment by julianlam** [comment]
Updated lavender, it should be 1.0.0, and require vanilla 1.0.0 as well. Not sure if this is related to your login page missing.

**Comment by kacemlight** [comment]
I updated lavender and vanilla to 1.0.0 but I have always the login page problem ... I cannot find a way to login into my admin panel ..

**Comment by kacemlight** [comment]
![capture d ecran 2015-02-10 a 20 34 55](https://cloud.githubusercontent.com/assets/10455208/6134076/f2ee9fa6-b15e-11e4-8890-3d3210412a73.png)
![capture d ecran 2015-02-10 a 20 34 43](https://cloud.githubusercontent.com/assets/10455208/6134077/f2f1102e-b15e-11e4-93e7-be5dee71019b.png)
![capture d ecran 2015-02-10 a 20 34 31](https://cloud.githubusercontent.com/assets/10455208/6134078/f2f4dace-b15e-11e4-8c42-6d14a88840ea.png)

**Comment by julianlam** [comment]
Hm... try posting a new topic in the community forum, as I believe you may get better help there.

**Comment by kacemlight** [comment]
Ok Thank you very much !!!!
