### ISSUE TITLE
No fields in my Nodebb Login page.. HELP PLEASE !

### ISSUE THREAD

**Issue by kacemlight** [NodeBB/nodebb-theme-vanilla#51]
I have a problem with my login page, there are no fields ?

login page NO FIELDS : 
![capture d ecran 2015-02-10 a 20 37 20](https://cloud.githubusercontent.com/assets/10455208/6134124/4941223e-b15f-11e4-86f1-9f579638c498.png)

Home page :
![capture d ecran 2015-02-10 a 20 34 55](https://cloud.githubusercontent.com/assets/10455208/6134076/f2ee9fa6-b15e-11e4-8890-3d3210412a73.png)

Tags Page:
![capture d ecran 2015-02-10 a 20 34 43](https://cloud.githubusercontent.com/assets/10455208/6134077/f2f1102e-b15e-11e4-93e7-be5dee71019b.png)

Reigster Page :
![capture d ecran 2015-02-10 a 20 34 31](https://cloud.githubusercontent.com/assets/10455208/6134078/f2f4dace-b15e-11e4-8c42-6d14a88840ea.png)

**Comment by julianlam** [comment]
Hey there,

I mean, [post a new topic here]! :smile: Sorry about that.
