### ISSUE TITLE
where partials/variables/ folder

### ISSUE THREAD

**Issue by cismous** [NodeBB/nodebb-theme-vanilla#52]
i can not find partials/variables/ folder!
please check https://github.com/NodeBB/nodebb-theme-vanilla/commit/46b732d5fe672d14eecfd815a6c87f6be422471e

**Comment by julianlam** [comment]
Your core NodeBB version is outdated. This commit hash should not have been
installable in order versions of NodeBB.

How did you install it?

**Comment by cismous** [comment]
npm install
My NodeBB version is v0.6.1

**Comment by cismous** [comment]
I have checkout the latest version, and then, i have know why!
