### ISSUE TITLE
Chat bug

### ISSUE THREAD

**Issue by delisey** [NodeBB/nodebb-theme-vanilla#57]
![bug](http://i.hizliresim.com/MyW7Ak.png)

when i click the chat, the chat box doesnt open as a small window (like the picture) but when i enlarge it the chat box opens

**Comment by julianlam** [comment]
Thanks for the report, addressing it now

**Comment by delisey** [comment]
didnt fix :(

**Comment by julianlam** [comment]
Please report your core commit hash and vanilla theme version

**Comment by delisey** [comment]
Nodebb-vanilla-theme version: 3.0.1
Nodebb version: 0.7.2
Link: timuu(.)com

**Comment by julianlam** [comment]
Run `git rev-parse HEAD` on your NodeBB directory to retrieve the commit hash.

**Comment by delisey** [comment]
[![image](http://i.hizliresim.com/DR4Vk3.jpg)](https://hizliresim.com/DR4Vk3)
