### ISSUE TITLE
Compile after modification

### ISSUE THREAD

**Issue by ayxos** [NodeBB/nodebb-theme-vanilla#92]
i have modified confirm.tpl to do a redirect after 3 seconds with this:

	<p><b>You will be redirected in 3 seconds</b></p>
	<script type="text/javascript">
		{literal}
		window.setTimeout( function() { 
			window.location = "https://www.interpretame.com/login"; 
		}, 3000);
		{/literal}	
	</script>

How can i compile the file to apply changes?

**Comment by pitaj** [comment]
Depends where you edited it.

`build/public/templates` is the destination for compiled templates, so editing files there won't work. You can add templates in your plugin that override existing templates. You need to run `./nodebb build` to rebuild assets, including templates.
